version: '3.8'

services:
  user-service:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: user-service  
    ports:
      - "3000:3000"  
    env_file:
      - ".env"
    volumes:
      - .:/app  
    restart: always 
